### ISSUE TITLE
 _reactNative.Keyboard.removeListener is not a function

### ISSUE THREAD

**Issue by younes0925** [FaridSafi/react-native-gifted-chat#2112]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-gifted-chat@0.16.3` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-gifted-chat/lib/MessageContainer.js b/node_modules/react-native-gifted-chat/lib/MessageContainer.js
index 193772a..e26443e 100644
--- a/node_modules/react-native-gifted-chat/lib/MessageContainer.js
+++ b/node_modules/react-native-gifted-chat/lib/MessageContainer.js
@@ -1,6 +1,6 @@
 import PropTypes from 'prop-types';
 import React from 'react';
-import { FlatList, View, StyleSheet, Keyboard, TouchableOpacity, Text, Platform, } from 'react-native';
+import { FlatList, View, StyleSheet, Keyboard, TouchableOpacity, Text, Platform } from 'react-native';
 import LoadEarlier from './LoadEarlier';
 import Message from './Message';
 import Color from './Color';
@@ -55,18 +55,26 @@ export default class MessageContainer extends React.PureComponent {
         this.attachKeyboardListeners = () => {
             const { invertibleScrollViewProps: invertibleProps } = this.props;
             if (invertibleProps) {
-                Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
-                Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
-                Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
-                Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
+                //Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
+                //Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
+                //Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
+                //Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
+                this.willShowSub = Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
+                this.didShowSub = Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
+                this.willHideSub = Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
+                this.didHideSub = Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
             }
         };
         this.detachKeyboardListeners = () => {
             const { invertibleScrollViewProps: invertibleProps } = this.props;
-            Keyboard.removeListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
-            Keyboard.removeListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
-            Keyboard.removeListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
-            Keyboard.removeListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
+            //Keyboard.removeListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
+            //Keyboard.removeListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
+            //Keyboard.removeListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
+            //Keyboard.removeListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
+            this.willShowSub?.remove();
+            this.didShowSub?.remove();
+            this.willHideSub?.remove();
+            this.didHideSub?.remove();
         };
         this.renderTypingIndicator = () => {
             if (Platform.OS === 'web') {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by younes0925** [comment]
_reactNative.Keyboard.removeListener is not a function

**Comment by teamzz111** [comment]
May you create a PR with these changes?

**Comment by momenfnnana** [comment]
same error occur with me when i upgraded react native version from 62 to 65

**Comment by tonydatw** [comment]
How can i fix this permanently? I have to replace the lines of code every time i update any package in the project

**Comment by Ralisson-Mattias** [comment]
Is the team still working on the library code?

**Comment by gshenar** [comment]
Any plans to get this fixed soon?

**Comment by ZainabShakeel** [comment]
Update MessageContainer.js with patch-package (install patch-package before)
step 1
-- vim node_modules/react-native-gifted-chat/lib/MessageContainer.js  (open file with vim filename .
Type i to switch into insert mode so that you can start editing the file.
Enter or modify the text with your file.
Once you're done, press the escape key Esc to get out of insert mode and back to command mode.
Type :wq to save and exit your file.

step 2 npx patch-package react-native-gifted-chat

run the app it will work fine

**Comment by joaocarmo** [comment]
You can also remove the following line, since it's no longer being used in `this.detachKeyboardListeners()`:

```js
const { invertibleScrollViewProps: invertibleProps } = this.props;
```

I also had to apply this fix, seems to work.

**Comment by ghadeerAqraa** [comment]
any update in this?

**Comment by Dasu-Uthpala** [comment]
after I deployed the changes, it won't work and gave the same error. what is the solution for that

**Comment by fukemy** [comment]
any update in new version, still got this error

**Comment by joaocarmo** [comment]
I've forked this project into [react-native-easy-chat](https://github.com/joaocarmo/react-native-easy-chat) which already includes a few fixes, so feel free to try it and submit PRs! It's actively maintained.

**Comment by fukemy** [comment]
@joaocarmo  i got this error when run EasyChat:
![Ảnh chụp Màn hình 2022-04-17 lúc 19 00 50](https://user-images.githubusercontent.com/8202437/163713486-5c3f6051-492d-46dd-9eb4-ee633f31edac.png)

**Comment by joaocarmo** [comment]
@fukemy you'll need to use React 17 or above with the new [JSX transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html), like [this](https://github.com/joaocarmo/react-native-easy-chat/blob/69bf3f44fbbca993b1be657951025f5142d87264/babel.config.js).

**Comment by fukemy** [comment]
thanks, above question were created when im new in React, now I can solved some small issues like this

**Comment by dkang23** [comment]
still exists with v 2.4.0

**Comment by Johan-dutoit** [comment]
@dkang23 can you create a new issue with a repro please.  Happy to look into it properly if this is still an issue.
